package com.example.localization

object Strings {
    private val STRINGS: Map<String, Map<String, String>> = mapOf(
        "app_title" to mapOf(
            "bn" to "জিরো-গ্রিড ফ্রিডম নেটওয়ার্ক",
            "en" to "Zero-Grid Freedom Network",
            "hi" to "ज़ीरो-ग्रिड फ़्रीडम नेटवर्क",
            "es" to "Red de Libertad Zero-Grid",
            "fr" to "Réseau Liberté Zero-Grid",
            "de" to "Zero-Grid Freiheitsnetzwerk",
            "pt" to "Rede de Liberdade Zero-Grid",
            "ar" to "شبكة زيرو-جريد للحرية",
            "zh" to "零网自由通信网络",
            "ja" to "ゼロ・グリッド・フリーダム・ネットワーク",
            "ko" to "제로-그리드 프리덤 네트워크",
            "ru" to "Сеть свободы Zero-Grid"
        ),
        "app_subtitle" to mapOf(
            "bn" to "গ্লোবাল ডিসেন্ট্রালাইজড অফলাইন মেশ",
            "en" to "Global Decentralized Offline Mesh",
            "hi" to "वैश्विक विकेंद्रीकृत ऑफ़लाइन मेश",
            "es" to "Malla Descentralizada Global Fuera de Línea",
            "fr" to "Réseau Maillé Décentralisé Mondial Hors-Ligne",
            "de" to "Globales Dezentrales Offline-Mesh",
            "pt" to "Malha Descentralizada Global Offline",
            "ar" to "شبكة مشفرة لا مركزية عالمية بدون إنترنت",
            "zh" to "全球去中心化无网对等网络",
            "ja" to "グローバル分散型オフラインメッシュ",
            "ko" to "글로벌 탈중앙화 오프라인 메시",
            "ru" to "Глобальная децентрализованная офлайн-сеть"
        ),
        "tab_home" to mapOf(
            "bn" to "হোম",
            "en" to "Home",
            "hi" to "होम",
            "es" to "Inicio",
            "fr" to "Accueil",
            "de" to "Start",
            "pt" to "Início",
            "ar" to "الرئيسية",
            "zh" to "主页",
            "ja" to "ホーム",
            "ko" to "홈",
            "ru" to "Главная"
        ),
        "tab_chat" to mapOf(
            "bn" to "মেসেজ",
            "en" to "Messages",
            "hi" to "संदेश",
            "es" to "Mensajes",
            "fr" to "Messages",
            "de" to "Nachrichten",
            "pt" to "Mensagens",
            "ar" to "الرسائل",
            "zh" to "消息",
            "ja" to "メッセージ",
            "ko" to "메시지",
            "ru" to "Сообщения"
        ),
        "tab_sos" to mapOf(
            "bn" to "এসওএস",
            "en" to "SOS",
            "hi" to "एसओएस",
            "es" to "SOS",
            "fr" to "SOS",
            "de" to "SOS",
            "pt" to "SOS",
            "ar" to "طوارئ SOS",
            "zh" to "紧急SOS",
            "ja" to "緊急SOS",
            "ko" to "긴급 SOS",
            "ru" to "SOS"
        ),
        "tab_map" to mapOf(
            "bn" to "ম্যাপ ও নোড",
            "en" to "Map & Nodes",
            "hi" to "मानचित्र एवं नोड्स",
            "es" to "Mapa y Nodos",
            "fr" to "Carte & Nœuds",
            "de" to "Karte & Knoten",
            "pt" to "Mapa e Nós",
            "ar" to "الخريطة والعقد",
            "zh" to "地图与节点",
            "ja" to "マップ＆ノード",
            "ko" to "지도 및 노드",
            "ru" to "Карта и узлы"
        ),
        "tab_nearby" to mapOf(
            "bn" to "নিকটবর্তী",
            "en" to "Nearby",
            "hi" to "आस-पास",
            "es" to "Cercanos",
            "fr" to "À proximité",
            "de" to "In der Nähe",
            "pt" to "Próximos",
            "ar" to "الأجهزة القريبة",
            "zh" to "附近设备",
            "ja" to "周辺端末",
            "ko" to "주변 기기",
            "ru" to "Рядом"
        ),
        "tab_files" to mapOf(
            "bn" to "ফাইল",
            "en" to "Files",
            "hi" to "फ़ाइलें",
            "es" to "Archivos",
            "fr" to "Fichiers",
            "de" to "Dateien",
            "pt" to "Arquivos",
            "ar" to "الملفات",
            "zh" to "文件",
            "ja" to "ファイル",
            "ko" to "파일",
            "ru" to "Файлы"
        ),
        "tab_settings" to mapOf(
            "bn" to "সেটিংস",
            "en" to "Settings",
            "hi" to "सेटिंग्स",
            "es" to "Ajustes",
            "fr" to "Paramètres",
            "de" to "Einstellungen",
            "pt" to "Configurações",
            "ar" to "الإعدادات",
            "zh" to "设置",
            "ja" to "設定",
            "ko" to "설정",
            "ru" to "Настройки"
        ),
        "tab_diagnostics" to mapOf(
            "bn" to "গ্লোবাল টেস্ট",
            "en" to "Global Test",
            "hi" to "ग्लोबल टेस्ट",
            "es" to "Prueba Global",
            "fr" to "Test Global",
            "de" to "Globaler Test",
            "pt" to "Teste Global",
            "ar" to "الاختبار العالمي",
            "zh" to "全球测试矩阵",
            "ja" to "グローバル検証",
            "ko" to "글로벌 검증",
            "ru" to "Тестирование"
        ),
        "global_truth_banner" to mapOf(
            "bn" to "জিরো-গ্রিড অবকাঠামো ছাড়া ম্যাজিকাল ইন্টারনেট তৈরি করে না। কাছাকাছি ডিভাইসগুলির মাধ্যমে লোকাল মেশ সংযোগ তৈরি হয়।",
            "en" to "Zero-Grid does not magically create global Internet. It operates device-to-device locally. Internet requires physical gateway backhaul.",
            "hi" to "ज़ीरो-ग्रिड बिना बुनियादी ढांचे के जादुई इंटरनेट नहीं बनाता। यह स्थानीय डिवाइस-टू-डिवाइस मेश पर काम करता है।",
            "es" to "Zero-Grid no crea Internet mágico sin infraestructura. Opera de dispositivo a dispositivo localmente.",
            "fr" to "Zero-Grid ne crée pas d'Internet magique sans infrastructure. Il fonctionne de pair à pair localement.",
            "de" to "Zero-Grid erzeugt kein magisches Internet ohne Infrastruktur. Es funktioniert lokal von Gerät zu Gerät.",
            "pt" to "Zero-Grid não cria Internet mágica sem infraestrutura. Opera localmente de dispositivo para dispositivo.",
            "ar" to "شبكة زيرو-جريد لا تخلق إنترنت سحرياً بدون بنية تحتية. تعمل محلياً من جهاز لآخر.",
            "zh" to "Zero-Grid 不会在没有实体基础设施的情况下凭空产生互联网。它依靠本地设备对设备通信。",
            "ja" to "Zero-Gridはインフラなしに魔法のようにインターネットを作るものではありません。近隣端末間でローカルに動作します。",
            "ko" to "Zero-Grid는 인프라 없이 마법처럼 인터넷을 생성하지 않습니다. 인접 기기 간 로컬 통신으로 작동합니다.",
            "ru" to "Zero-Grid не создает интернет без инфраструктуры. Сеть работает локально от устройства к устройству."
        ),
        "network_layer_offline" to mapOf(
            "bn" to "লোকাল অফলাইন মেশ (ইন্টারনেট নেই)",
            "en" to "Local Offline Mesh (No Internet)",
            "hi" to "स्थानीय ऑफ़लाइन मेश (इंटरनेट नहीं)",
            "es" to "Malla Local Fuera de Línea (Sin Internet)",
            "fr" to "Réseau Maillé Local Hors-Ligne (Pas d'Internet)",
            "de" to "Lokales Offline-Mesh (Kein Internet)",
            "pt" to "Malha Local Offline (Sem Internet)",
            "ar" to "شبكة مشفرة محلية (بدون إنترنت)",
            "zh" to "本地无网对等网 (无互联网)",
            "ja" to "ローカル・オフライン・メッシュ (インターネットなし)",
            "ko" to "로컬 오프라인 메시 (인터넷 없음)",
            "ru" to "Локальная офлайн-сеть (Без интернета)"
        ),
        "network_layer_gateway" to mapOf(
            "bn" to "ইন্টারনেট গেটওয়ে নোড সংযুক্ত",
            "en" to "Internet Gateway Node Connected",
            "hi" to "इंटरनेट गेटवे नोड कनेक्टेड",
            "es" to "Nodo Puerta de Enlace a Internet Conectado",
            "fr" to "Nœud Passerelle Internet Connecté",
            "de" to "Internet-Gateway-Knoten verbunden",
            "pt" to "Nó Gateway de Internet Conectado",
            "ar" to "بوابة إنترنت متصلة",
            "zh" to "互联网网关节点已连接",
            "ja" to "インターネット・ゲートウェイ・ノード接続済",
            "ko" to "인터넷 게이트웨이 노드 연결됨",
            "ru" to "Подключен шлюз интернета"
        ),
        "network_layer_global" to mapOf(
            "bn" to "গ্লোবাল ব্যাকহোল উপলব্ধ",
            "en" to "Global Internet Backhaul Available",
            "hi" to "वैश्विक इंटरनेट बैकहॉल उपलब्ध",
            "es" to "Red troncal de Internet global disponible",
            "fr" to "Liaison Internet globale disponible",
            "de" to "Globales Internet-Backhaul verfügbar",
            "pt" to "Backhaul de Internet Global Disponível",
            "ar" to "اتصال شبكي عالمي متوفر",
            "zh" to "全球互联网回程链路可用",
            "ja" to "グローバル・バックホール利用可能",
            "ko" to "글로벌 인터넷 백홀 사용 가능",
            "ru" to "Доступен глобальный интернет"
        ),
        "sos_title" to mapOf(
            "bn" to "জরুরি এসওএস অ্যালার্ট",
            "en" to "Emergency SOS Alert",
            "hi" to "आपातकालीन एसओएस अलर्ट",
            "es" to "Alerta de Emergencia SOS",
            "fr" to "Alerte d'Urgence SOS",
            "de" to "Notfall-SOS-Alarm",
            "pt" to "Alerta de Emergência SOS",
            "ar" to "نداء استغاثة طارئ SOS",
            "zh" to "紧急 SOS 广播",
            "ja" to "緊急 SOS アラート",
            "ko" to "긴급 SOS 경보",
            "ru" to "Экстренный сигнал SOS"
        ),
        "sos_prompt_confirm" to mapOf(
            "bn" to "আপনি কি নিশ্চিত যে নিকটবর্তী সব নোডে এসওএস সম্প্রচার করতে চান?",
            "en" to "Are you sure you want to broadcast an SOS to all nearby nodes?",
            "hi" to "क्या आप वाकई आस-पास के सभी नोड्स पर एसओएस प्रसारित करना चाहते हैं?",
            "es" to "¿Seguro que desea transmitir un SOS a todos los nodos cercanos?",
            "fr" to "Êtes-vous sûr de vouloir diffuser un SOS à tous les nœuds proches?",
            "de" to "Möchten Sie wirklich einen SOS-Alarm an alle Knoten senden?",
            "pt" to "Tem certeza de que deseja transmitir um SOS para todos os nós próximos?",
            "ar" to "هل أنت متأكد من رغبتك في إرسال نداء استغاثة لجميع العقد القريبة؟",
            "zh" to "确认向附近所有节点广播紧急 SOS 吗？",
            "ja" to "近隣の全ノードへ緊急SOSを発信してもよろしいですか？",
            "ko" to "주변의 모든 노드로 긴급 SOS를 전송하시겠습니까?",
            "ru" to "Вы уверены, что хотите отправить сигнал SOS всем узлам рядом?"
        ),
        "sos_status_created" to mapOf(
            "bn" to "এসওএস তৈরি হয়েছে",
            "en" to "SOS Created",
            "hi" to "एसओएस बनाया गया",
            "es" to "SOS Creado",
            "fr" to "SOS Créé",
            "de" to "SOS erstellt",
            "pt" to "SOS Criado",
            "ar" to "تم إنشاء الاستغاثة",
            "zh" to "SOS已创建",
            "ja" to "SOS作成完了",
            "ko" to "SOS 생성됨",
            "ru" to "Сигнал SOS создан"
        ),
        "sos_status_sending" to mapOf(
            "bn" to "সম্প্রচারিত হচ্ছে...",
            "en" to "Broadcasting...",
            "hi" to "प्रसारित हो रहा है...",
            "es" to "Transmitiendo...",
            "fr" to "Diffusion en cours...",
            "de" to "Senden...",
            "pt" to "Transmitindo...",
            "ar" to "جارٍ البث...",
            "zh" to "正在广播...",
            "ja" to "送信中...",
            "ko" to "전송 중...",
            "ru" to "Передача..."
        ),
        "sos_status_relaying" to mapOf(
            "bn" to "রিলে নোডের মাধ্যমে অগ্রসরমান",
            "en" to "Relaying via Nodes",
            "hi" to "नोड्स द्वारा रिले हो रहा है",
            "es" to "Retransmitiendo por nodos",
            "fr" to "Relais via les nœuds",
            "de" to "Weiterleitung über Knoten",
            "pt" to "Retransmitindo pelos nós",
            "ar" to "جارٍ التمرير عبر العقد",
            "zh" to "正在通过中继节点转发",
            "ja" to "ノード経由で中継中",
            "ko" to "노드를 통해 릴레이 중",
            "ru" to "Ретрансляция через узлы"
        ),
        "sos_status_delivered" to mapOf(
            "bn" to "কাছাকাছি নোডে পৌঁছেছে",
            "en" to "Delivered to Local Nodes",
            "hi" to "स्थानीय नोड्स तक पहुँच गया",
            "es" to "Entregado a nodos locales",
            "fr" to "Livré aux nœuds locaux",
            "de" to "An lokale Knoten übermittelt",
            "pt" to "Entregue aos nós locais",
            "ar" to "تم التسليم للعقد المحلية",
            "zh" to "已成功送达附近节点",
            "ja" to "ローカルノードへ到達",
            "ko" to "로컬 노드에 전달됨",
            "ru" to "Доставлено локальным узлам"
        ),
        "sos_status_offline" to mapOf(
            "bn" to "কোনো নোড পাওয়া যায়নি (ক্যাশে জমা আছে)",
            "en" to "No Nodes in Range (Queued in Store & Forward)",
            "hi" to "कोई नोड सीमा में नहीं (कतार में सहेजा गया)",
            "es" to "Sin nodos al alcance (En cola de almacenamiento)",
            "fr" to "Aucun nœud à portée (En file d'attente)",
            "de" to "Kein Knoten in Reichweite (Gespeichert)",
            "pt" to "Nenhum nó ao alcance (Na fila)",
            "ar" to "لا توجد عقد في النطاق (مخزن لإعادة التمرير)",
            "zh" to "范围内暂无节点（已暂存待转发）",
            "ja" to "通信圏内にノードなし (保存＆転送キュー)",
            "ko" to "범위 내 노드 없음 (저장 후 전송 대기)",
            "ru" to "Нет узлов в зоне (в очереди)"
        ),
        "security_badge" to mapOf(
            "bn" to "হার্ডওয়্যার কী-স্টোর এনক্রিপশন (RSA-2048 + AES-GCM)",
            "en" to "Hardware KeyStore Crypto (RSA-2048 + AES-GCM)",
            "hi" to "हार्डवेयर की-स्टोर एन्क्रिप्शन (RSA-2048 + AES-GCM)",
            "es" to "Criptografía KeyStore por Hardware (RSA-2048 + AES-GCM)",
            "fr" to "Chiffrement Matériel KeyStore (RSA-2048 + AES-GCM)",
            "de" to "Hardware-KeyStore-Verschlüsselung (RSA-2048 + AES-GCM)",
            "pt" to "Criptografia de Hardware KeyStore (RSA-2048 + AES-GCM)",
            "ar" to "تشفير عتادي آمن (RSA-2048 + AES-GCM)",
            "zh" to "硬件 KeyStore 加密保护 (RSA-2048 + AES-GCM)",
            "ja" to "ハードウェアKeyStore暗号化 (RSA-2048 + AES-GCM)",
            "ko" to "하드웨어 키스토어 암호화 (RSA-2048 + AES-GCM)",
            "ru" to "Аппаратное шифрование KeyStore (RSA-2048 + AES-GCM)"
        ),
        "security_disclaimer" to mapOf(
            "bn" to "বাস্তবসম্মত নিরাপত্তা নীতি: কোনো সিস্টেম ১০০% অপূরণীয় বা অভেদ্য নয়। শক্তিশালী ক্রিপ্টোগ্রাফি ও লোকাল প্রাইভেসি দ্বারা সুরক্ষিত।",
            "en" to "Realistic Security Notice: No system is 100% unhackable. Zero-Grid uses hardware-backed keys and zero telemetry for maximum resilience.",
            "hi" to "सुरक्षा सूचना: कोई भी प्रणाली 100% अभेद्य नहीं होती। ज़ीरो-ग्रिड हार्डवेयर कुंजियों और शून्य टेलीमेट्री का उपयोग करता है।",
            "es" to "Aviso de Seguridad: Ningún sistema es 100% invulnerable. Zero-Grid utiliza claves de hardware y cero telemetría.",
            "fr" to "Avis de Sécurité: Aucun système n'est invulnérable à 100%. Zero-Grid s'appuie sur le chiffrement matériel sans télémétrie.",
            "de" to "Sicherheitshinweis: Kein System ist zu 100% unhackbar. Zero-Grid nutzt Hardware-Schlüssel und null Telemetrie.",
            "pt" to "Aviso de Segurança: Nenhum sistema é 100% inviolável. O Zero-Grid usa chaves de hardware e zero telemetria.",
            "ar" to "تنبيه الأمان: لا يوجد نظام غير قابل للاختراق بنسبة 100%. تعتمد المنصة على تشفير عتادي قوي وبدون تتبع.",
            "zh" to "真实安全声明：任何系统均无法声称绝对绝对不可攻破。Zero-Grid 依靠芯片级安全密钥与零隐私上传提供强力保护。",
            "ja" to "セキュリティに関する現実的告知: 100%絶対に破られないシステムは存在しません。Zero-Gridはハードウェア鍵とゼロ・テレメトリで安全性を最大化します。",
            "ko" to "현실적인 보안 고지: 100% 해킹 불가능한 시스템은 없습니다. Zero-Grid는 하드웨어 보안 키와 제로 원격측정으로 안전성을 제공합니다.",
            "ru" to "Уведомление о безопасности: Ни одна система не является на 100% невзламываемой. Zero-Grid использует аппаратные ключи и нулевую телеметрию."
        ),
        "low_bandwidth_title" to mapOf(
            "bn" to "কম ব্যান্ডউইথ মোড (দুর্যোগ ও দূরবর্তী অঞ্চল)",
            "en" to "Low-Bandwidth Mode (Disaster & Remote)",
            "hi" to "कम बैंडविड्थ मोड (आपदा एवं दूरस्थ क्षेत्र)",
            "es" to "Modo de Bajo Ancho de Banda (Desastre y Remoto)",
            "fr" to "Mode Faible Bande Passante (Catastrophe et Isolé)",
            "de" to "Niedrige-Bandbreite-Modus (Katastrophe & Abgelegen)",
            "pt" to "Modo de Baixa Largura de Banda (Desastre e Remoto)",
            "ar" to "وضع النطاق الترددي المنخفض (الكوارث والمناطق النائية)",
            "zh" to "低带宽节能模式（适用于灾难与偏远地区）",
            "ja" to "低帯域モード (災害・遠隔地対応)",
            "ko" to "저대역폭 모드 (재난 및 오지)",
            "ru" to "Режим низкой пропускной способности (ЧС и удаленные районы)"
        ),
        "low_bandwidth_desc" to mapOf(
            "bn" to "টেক্সট ও এসওএস অগ্রাধিকার পায়; ব্যাকগ্রাউন্ড ফাইল ও ভয়েস ট্রাফিকের আকার সীমিত রাখা হয়।",
            "en" to "Prioritizes Text and SOS; suspends non-essential telemetry and large media chunks to conserve battery and spectrum.",
            "hi" to "टेक्स्ट और एसओएस को प्राथमिकता; बैटरी और स्पेक्ट्रम बचाने के लिए मीडिया चंक्स को सीमित करता है।",
            "es" to "Prioriza Texto y SOS; suspende telemetría no esencial y medios pesados para ahorrar batería.",
            "fr" to "Donne priorité au texte et au SOS; réduit la télémétrie et les fichiers pour économiser l'énergie.",
            "de" to "Priorisiert Text und SOS; pausiert große Mediendateien zum Sparen von Energie und Funkbandbreite.",
            "pt" to "Prioriza Texto e SOS; suspende tráfego pesado para economizar bateria e espectro.",
            "ar" to "يعطي الأولوية للنصوص والاستغاثة؛ ويوقف حركة البيانات غير الضرورية لتوفير الطاقة.",
            "zh" to "优先保证文本和 SOS 传输；暂停非必要遥测与大容量文件，节省能耗与频段。",
            "ja" to "テキストとSOSを最優先；電力と帯域幅を節約するため大容量ファイルの送受信を制限します。",
            "ko" to "텍스트 및 SOS 최우선 처리; 배터리와 스펙트럼 절약을 위해 대용량 미디어를 제한합니다.",
            "ru" to "Приоритет текста и SOS; приостанавливает передачу тяжелых файлов для экономии энергии."
        ),
        "guest_mode_badge" to mapOf(
            "bn" to "গেস্ট মোড (সিম কার্ড বা ফোন নম্বর প্রয়োজন নেই)",
            "en" to "Guest Mode (No SIM or Phone Number Required)",
            "hi" to "गेस्ट मोड (सिम या फोन नंबर आवश्यक नहीं)",
            "es" to "Modo Invitado (No se requiere SIM ni teléfono)",
            "fr" to "Mode Invité (Aucune carte SIM ou numéro requis)",
            "de" to "Gast-Modus (Keine SIM-Karte oder Nummer nötig)",
            "pt" to "Modo Convidado (Sem necessidade de SIM ou telefone)",
            "ar" to "وضع الضيف (لا يشترط شريحة SIM أو رقم هاتف)",
            "zh" to "访客设备模式（无需 SIM 卡或手机号）",
            "ja" to "ゲストモード (SIMカードや電話番号は不要)",
            "ko" to "게스트 모드 (SIM 카드 또는 전화번호 불필요)",
            "ru" to "Гостевой режим (Не требуется SIM-карта или телефон)"
        ),
        "unit_metric" to mapOf(
            "bn" to "মেট্রিক (কিমি, মিটার, °সে)",
            "en" to "Metric (km, m, °C)",
            "hi" to "मीट्रिक (किमी, मीटर, °C)",
            "es" to "Métrico (km, m, °C)",
            "fr" to "Métrique (km, m, °C)",
            "de" to "Metrisch (km, m, °C)",
            "pt" to "Métrico (km, m, °C)",
            "ar" to "متري (كم، متر، °م)",
            "zh" to "公制 (km, m, °C)",
            "ja" to "メートル法 (km, m, °C)",
            "ko" to "미터법 (km, m, °C)",
            "ru" to "Метрическая (км, м, °C)"
        ),
        "unit_imperial" to mapOf(
            "bn" to "ইম্পেরিয়াল (মাইল, ফুট, °ফা)",
            "en" to "Imperial (mi, ft, °F)",
            "hi" to "इंपीरियल (मील, फीट, °F)",
            "es" to "Imperial (mi, ft, °F)",
            "fr" to "Impérial (mi, ft, °F)",
            "de" to "Imperial (mi, ft, °F)",
            "pt" to "Imperial (mi, ft, °F)",
            "ar" to "إمبراطوري (ميل، قدم، °ف)",
            "zh" to "英制 (mi, ft, °F)",
            "ja" to "ヤード・ポンド法 (mi, ft, °F)",
            "ko" to "야드파운드법 (mi, ft, °F)",
            "ru" to "Британская (миль, фут, °F)"
        ),
        "community_node_header" to mapOf(
            "bn" to "গ্লোবাল কমিউনিটি ও সোলার নোড",
            "en" to "Global Community & Solar Nodes",
            "hi" to "ग्लोबल कम्युनिटी एवं सोलर नोड्स",
            "es" to "Nodos Comunitarios y Solares Globales",
            "fr" to "Nœuds Communautaires et Solaires Mondiaux",
            "de" to "Globale Gemeinschafts- & Solarknoten",
            "pt" to "Nós Comunitários e Solares Globais",
            "ar" to "عقد المجتمع المحلي والطاقة الشمسية",
            "zh" to "全球社区与太阳能基站节点",
            "ja" to "グローバル・コミュニティ＆ソーラーノード",
            "ko" to "글로벌 커뮤니티 및 태양광 노드",
            "ru" to "Глобальные общественные и солнечные узлы"
        ),
        "solar_recommended_note" to mapOf(
            "bn" to "সোলার হাব স্পেসিফিকেশন: উদাহরণ ও সুপারিশকৃত ডিজাইন (শারীরিকভাবে মাঠপর্যায়ে পরীক্ষা না করা পর্যন্ত)।",
            "en" to "Solar Hub Architecture: Example / Recommended design (pending physical field deployment verification).",
            "hi" to "सोलर हब आर्किटेक्चर: उदाहरण एवं अनुशंसित डिज़ाइन (फ़ील्ड सत्यापन तक)।",
            "es" to "Arquitectura Solar Hub: Diseño de ejemplo / recomendado.",
            "fr" to "Architecture Solaire Hub : Conception d'exemple / recommandée.",
            "de" to "Solar-Hub-Architektur: Beispiel- & Empfohlenes Design.",
            "pt" to "Arquitetura Solar Hub: Projeto de exemplo / recomendado.",
            "ar" to "بنية محطة الطاقة الشمسية: تصميم نموذجي وموصى به.",
            "zh" to "太阳能基站架构：示范与推荐配置（在完成实体部署前作为技术参考）。",
            "ja" to "ソーラーハブ構成: 推奨サンプル設計 (実機フィールド検証前)。",
            "ko" to "태양광 허브 아키텍처: 권장 예시 설계 (현장 검증 기준).",
            "ru" to "Архитектура солнечного узла: Пример / Рекомендуемая схема."
        ),
        "country_region_label" to mapOf(
            "bn" to "দেশ ও অঞ্চল নির্বাচন",
            "en" to "Country & Region Selection",
            "hi" to "देश एवं क्षेत्र चयन",
            "es" to "Selección de País y Región",
            "fr" to "Sélection du Pays et de la Région",
            "de" to "Länder- & Regionsauswahl",
            "pt" to "Seleção de País e Região",
            "ar" to "اختيار الدولة والمنطقة",
            "zh" to "国家与地区配置",
            "ja" to "国・地域の設定",
            "ko" to "국가 및 지역 설정",
            "ru" to "Выбор страны и региона"
        ),
        "timezone_label" to mapOf(
            "bn" to "সময় অঞ্চল (Time Zone)",
            "en" to "Time Zone",
            "hi" to "समय क्षेत्र (Time Zone)",
            "es" to "Zona Horaria",
            "fr" to "Fuseau Horaire",
            "de" to "Zeitzone",
            "pt" to "Fuso Horário",
            "ar" to "المنطقة الزمنية",
            "zh" to "时区设置",
            "ja" to "タイムゾーン",
            "ko" to "시간대",
            "ru" to "Часовой пояс"
        ),
        "language_label" to mapOf(
            "bn" to "ভাষা পরিবর্তন",
            "en" to "Language",
            "hi" to "भाषा बदलें",
            "es" to "Idioma",
            "fr" to "Langue",
            "de" to "Sprache",
            "pt" to "Idioma",
            "ar" to "تغيير اللغة",
            "zh" to "界面语言",
            "ja" to "言語選択",
            "ko" to "언어 선택",
            "ru" to "Язык интерфейса"
        ),
        "emergency_contacts_title" to mapOf(
            "bn" to "বিশ্বস্ত জরুরি কন্টাক্টসমূহ",
            "en" to "Configurable Emergency Contacts",
            "hi" to "कॉन्फ़िगर करने योग्य आपातकालीन संपर्क",
            "es" to "Contactos de Emergencia Configurables",
            "fr" to "Contacts d'Urgence Configurables",
            "de" to "Konfigurierbare Notfallkontakte",
            "pt" to "Contatos de Emergência Configuráveis",
            "ar" to "جهات اتصال الطوارئ المعتمدة",
            "zh" to "自定义紧急联络人",
            "ja" to "緊急連絡先の個別設定",
            "ko" to "긴급 연락처 설정",
            "ru" to "Настраиваемые экстренные контакты"
        ),
        "emergency_confirmation_req" to mapOf(
            "bn" to "জরুরি নম্বরে কল বা মেসেজের পূর্বে ইউজার নিশ্চিতকরণ বাধ্যতামূলক।",
            "en" to "User confirmation is strictly required before placing emergency calls.",
            "hi" to "आपातकालीन नंबरों पर कॉल से पहले उपयोगकर्ता पुष्टि अनिवार्य है।",
            "es" to "Se requiere confirmación del usuario antes de realizar llamadas de emergencia.",
            "fr" to "La confirmation de l'utilisateur est requise avant d'appeler les urgences.",
            "de" to "Benutzerbestätigung vor Notrufen zwingend erforderlich.",
            "pt" to "A confirmação do usuário é estritamente necessária antes de ligar para emergência.",
            "ar" to "يلزم تأكيد المستخدم قبل إجراء أي مكالمة طوارئ.",
            "zh" to "拨打紧急电话前必须经过用户手动确认。",
            "ja" to "緊急発信の前にユーザーの明示的な確認が必要です。",
            "ko" to "긴급 통화 연결 전 사용자의 확인이 반드시 필요합니다.",
            "ru" to "Перед вызовом экстренных служб требуется подтверждение пользователя."
        )
    )

    fun get(key: String, lang: String): String {
        val entry = STRINGS[key] ?: return key
        return entry[lang] ?: entry["en"] ?: key
    }
}
